platform :ios, '8.0'
use_frameworks!

target 'TKKeyboardControl_Example' do
  pod 'TKKeyboardControl', :path => '..'
end

target 'TKKeyboardControl_Tests' do
  pod 'TKKeyboardControl', :path => '..'
end
